version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  target-branch: master
